### ISSUE TITLE
How to set up on ampere instance 

### ISSUE THREAD

**Issue by aless3** [maurice-w/opnsense-vm-images#2]
Ehi, sorry to trouble you, but what are the suggested values when uploading to oci for use on the ampere vm?

I downloaded the build, uncompressed it, and uploaded the file to an oci bucket.
Then I created a custom image and added the flex vm to the image shapes.
But I cannot ssh into it, even after allowing all incoming traffic (cannot even ping the ip) 

The main thing is keeping me back I think is the values to set for the custom image, like the "operating system" value, considering there is no freebsd option.
I am setting operating system to generic Linux now, is this correct? are there some other options you modified? do you have any advice?

thank you very much for your work!

edit: I have just seen you just released the 24.x version, this was done on the 23.x line, now testing with 24.x
same issues...

**Comment by maurice-w** [comment]
"Generic Linux" ist what I use, too. Make sure to enable UEFI_64 after importing the image. The default is BIOS, which isn't supported by Ampere instances.
I recommend using a *-ufs-serial-vm-aarch64.qcow2 image. This allows using the Oracle Cloud Shell for initial setup (assigning the WAN interface and changing the root password). After that, you should be able to access the Web UI (initially only via IPv6, since Oracle's IPv4 SNAT prevents accessing the OPNsense Web UI with default settings).

**Comment by aless3** [comment]
Thank you, it works!

**Comment by tkkost** [comment]
I just leave a message here for other novices. 
If you have "_The HTTP_REFERER "https://xx.xx.xx.xx/" does not match the predefined settings. You can disable this check if needed under System: Settings: Administration_." error and you can't access web-ui.
If you don't have ipv6 address and you have a console, you can manually edit file /conf/config.xml.
You need to insert next
`      <http_referer_check>1</http_referer_check>`
inside to chapter about webui.
For example:
```
<webgui>
      <protocol>https</protocol>
      <nohttpreferercheck>1</nohttpreferercheck>
      <nodnsrebindcheck>1</nodnsrebindcheck>
</webgui>
```

**Comment by aless3** [comment]
I wrote this sed command:
```sed -i'.bak' 's|<protocol>https</protocol>|<protocol>https</protocol>\n      <nohttpreferercheck>1</nohttpreferercheck>|g' config.xml```
where config.xml is the config file, a backup is saved as config.xml.bak
this adds after ```<protocol>https</protocol>``` the line ```<nohttpreferercheck>1</nohttpreferercheck> ```, using as separator the pipe character instead of the usual slash character (there are slashes in the query, it doesn't work)
not sure if this is the right place to post, but since this was a change recently suggested in this thread this can automate the task without having to use vim/nano (iirc the image doesn't have nano)

**Comment by maurice-w** [comment]
The image does have ee, a very fine editor. :-)
