### ISSUE TITLE
Request: Any way to include Unbound extended blocklist functionality (from OPNsense business edition) in these builds?

### ISSUE THREAD

**Issue by gspannu** [maurice-w/opnsense-vm-images#3]
Is there any way to include the functionality available in OPNsense business build (i.e. Unbound [extended blocklists](https://docs.opnsense.org/vendor/deciso/extended_dnsbl.html)) in this image?

I am specifically looking for Unbound extended blocklists to be available in OPNsense community edition?

**Anyway to achieve this?
Or any help to to run some patch in the existing OPNsense community installation to achieve the same?**

_I am only looking to use the Unbound functionality from OPNsense business edition in my community version?_ 

Thanks..

**Comment by maurice-w** [comment]
If you have a valid subscription, you can use one of the amd64 VM images and switch it to Business Edition (System: Firmware: Settings).

But if you're asking for integrating Business Edition features into the Community Edition: This is really unrelated to VM images and definitely not something I'm going to do, sorry.

**Comment by gspannu** [comment]
Thank you for your prompt response. 

I do not need the business features (as such) of OPnsense, I am a home user.

What I would have liked to try and experiment with is a specific feature of enhanced blocking configuration in Unbound that is available in the Business edition.

_In previous versions (Community edition) of OPNsense, one could customise Unbound with in-folder scripts, and I could have achieved the same outcome -  but unfortunately with the latest version (24.x), this is not possible as it is not possible to customise Unbound._

Hence, my request.

_This request was not to undermine the Business edition or get a freebie or to compromise anyone's integrity..._

**Comment by maurice-w** [comment]
I'm still not sure what exactly you are asking for. This repository is a fork of opnsense/tools, which provides the tools required for building OPNsense. Nothing more, nothing less. You can use the tools to add additional packages and plugins to OPNsense images, but which specific package(s) would you like to be added? Can you provide a link?

**Comment by gspannu** [comment]
What I am looking for is to use Unbound plugin of the Business edition in the Community edition or some means of manually trying out the extra features (Unbound extended Blocklist), without having to use Business Edition?

_The Unbound functionality in OPNsense Buisness edition is slightly different from what is available in the Community edition._

I was wondering if a specific (temporary) build could be made for this, so that one could try the features.

Or anyway to inject the OPNsense Business edition Unbound plugin into the Community edition?
