### ISSUE TITLE
raspberry pi 4 issues with update firmware to 24.7.6 and 24.7.7

### ISSUE THREAD

**Issue by mrusli70** [maurice-w/opnsense-vm-images#4]
Hi 

I am running opnsense with raspberry pi 4 from version 24.7.4 and having issues when upgrading firmware to 24.7.6 and to the latest version 24.7.7 because i cannot seems to access to my email via gmail and after upgrading the firmwaere from 24.7.6 to the latest version 24.7.7 the kernel cannot seems to boot. I have to edit the /boot/defaults/loader.conf files and use the kernel.old instead of kernel.

**Comment by maurice-w** [comment]
24.7.7 is a minor update and doesn't include a new kernel, so it seems unlikely that updating from 24.7.6 is the cause for a boot failure.
Not sure how Gmail issues are supposed to be related to OPNsense.

Please also keep in mind that this is a virtual machine image repository. I don't provide support for bare metal installations here.

**Comment by mrusli70** [comment]
I have to redo the whole thing again from scratch back to square one and do a opnsense-revert -r 24.7.5 opnsense in order to get the gmail to be able to login. And I have tried many times that after upgrade to the latest firmware version to 24.7.6 and to 24.7.7 having my gmail unable to login at all and keep prompting for google code to be send. But once i redo and revert back to the old version every thing is back to normal and i able to access my gmail email account.

**Comment by maurice-w** [comment]
Completely unrelated to this fork of opnsense/tools, which is explicitly about building OPNsense VM images only. Please stop spamming random repos with unspecific issues.
