### ISSUE TITLE
Initial configuration after first boot?

### ISSUE THREAD

**Issue by fdcastel** [maurice-w/opnsense-vm-images#5]
After the initial startup of the virtual machine, **how can one automate the initial configuration**? 

I typically use `cloud-init` for this purpose; however, to the best of my knowledge, OPNsense does not include it. 

Any simple method to load a custom `config.xml` file on the first boot would be sufficient.

Using the latest `vhdx` image from the [Releases](https://github.com/maurice-w/opnsense-vm-images/releases) section.

**Comment by maurice-w** [comment]
These VM images behave the same as a traditional OPNsense installation, no additional tools (like cloud-init) are included. You can import a config.xml during first boot, that's a somewhat interactive process though (see the official docs).

If you plan to deploy OPNsense on Azure: There is an official image with additional integration features.

**Comment by fdcastel** [comment]
Thank you, @maurice-w, for the prompt information.

I’m aiming to deploy in my local environment (Proxmox VE) rather than on Azure. 

My goal is to set up a router that’s fully configured with a single command, requiring no manual console interaction. 

Do you know if there’s a way to "inject" a script into the VHDX image so it executes automatically on the first boot? 

Perhaps some kind of "hook" that I could use?

**Comment by fdcastel** [comment]
Unfortunately, it seems that work on integrating cloud-init with FreeBSD has stalled since January 2024, according to [this report](https://www.freebsd.org/status/report-2024-01-2024-03/cloud-init/). That's why I'm asking you this.

Looking at the Azure image [installation instructions](https://docs.opnsense.org/manual/how-tos/installazure.html), it appears they may have addressed this issue. The Azure setup wizard allows users to input network settings, which must be incorporated into the image in some manner in the first boot.

**Comment by maurice-w** [comment]
You could mount the image and inject a config.xml (/conf/config.xml). This would probably be easiest when using a FreeBSD host. UFS write access is somewhat problematic on other operating systems.

**Comment by fdcastel** [comment]
Understood. Thank you, @maurice-w! 👍🏻
